#!/usr/bin/env bash
#
# Writes .env.local from the running local Supabase stack.
#
# Run after `npx supabase start`. Reads the credentials from `supabase status`
# rather than hardcoding them, because the local anon/service keys changed format
# in recent CLI versions and a stale hardcoded key produces a confusing 401
# rather than an obvious failure.
#
# The keys this writes are LOCAL DEVELOPMENT keys for a container on your machine.
# They are not secrets and are not the same as any hosted project's keys.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if ! npx supabase status >/dev/null 2>&1; then
  echo "Local Supabase is not running. Start it first:" >&2
  echo "  npx supabase start" >&2
  exit 1
fi

STATUS="$(npx supabase status -o env 2>/dev/null)"

read_value() {
  # `supabase status -o env` emits KEY="value" lines.
  printf '%s\n' "$STATUS" | grep -E "^$1=" | head -1 | cut -d= -f2- | tr -d '"'
}

API_URL="$(read_value 'API_URL')"
ANON_KEY="$(read_value 'ANON_KEY')"
SERVICE_KEY="$(read_value 'SERVICE_ROLE_KEY')"

if [ -z "$API_URL" ] || [ -z "$ANON_KEY" ] || [ -z "$SERVICE_KEY" ]; then
  echo "Could not read credentials from 'supabase status -o env'." >&2
  printf '%s\n' "$STATUS" >&2
  exit 1
fi

# The mobile app runs on a device or emulator, which cannot reach the host's
# 127.0.0.1. An Android emulator reaches the host at 10.0.2.2; a physical device
# needs the machine's LAN address. Both are noted rather than guessed, because
# picking the wrong one produces a silent "cannot reach server" at sign-in.
LAN_IP="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo '')"

# Env files are written PER APP, not just at the repo root, because Next.js and
# Expo each read `.env.local` from their own directory — a root-only file is
# silently ignored by both.
#
# Splitting them is also the safer shape: apps/mobile/.env.local contains no
# service-role key at all, so there is nothing for a mobile bundle to leak even by
# mistake.

write_header() {
  cat <<HEADER
# =============================================================================
# Generated by scripts/local-env.sh — LOCAL DEVELOPMENT ONLY. Do not commit.
# =============================================================================
# Credentials for the Supabase stack running in Docker on this machine. These are
# well-known local development values, not secrets, and are unrelated to any
# hosted project.
#
# Regenerate after 'supabase stop && supabase start':  ./scripts/local-env.sh
# =============================================================================

HEADER
}

# --- Admin dashboard: runs on this machine, so localhost is correct -----------
{
  write_header
  cat <<ENV
NEXT_PUBLIC_SUPABASE_URL=$API_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
NEXT_PUBLIC_APP_ENV=local

# Server-only. Bypasses row-level security. Never prefix this with NEXT_PUBLIC_.
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_KEY
ENV
} > apps/admin/.env.local

# --- Mobile app: no privileged key, by construction --------------------------
{
  write_header
  cat <<ENV
# Expo Web and the iOS simulator can reach localhost. A device or Android emulator
# cannot — swap the URL for your target:
#   Android emulator : http://10.0.2.2:54321
#   Physical device  : ${LAN_IP:+http://$LAN_IP:54321}${LAN_IP:-http://<your-lan-ip>:54321}
EXPO_PUBLIC_SUPABASE_URL=$API_URL
EXPO_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
EXPO_PUBLIC_APP_ENV=local
ENV
} > apps/mobile/.env.local

# --- Repo root: for scripts and turbo ----------------------------------------
{
  write_header
  cat <<ENV
NEXT_PUBLIC_SUPABASE_URL=$API_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
NEXT_PUBLIC_APP_ENV=local
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_KEY
EXPO_PUBLIC_SUPABASE_URL=$API_URL
EXPO_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
EXPO_PUBLIC_APP_ENV=local
BONCHI_TEST_DB_PORT=55432
ENV
} > .env.local

echo "✓ Wrote .env.local, apps/admin/.env.local, apps/mobile/.env.local"
echo ""
echo "  API      $API_URL"
echo "  Studio   http://localhost:54323"
echo "  Mail     http://localhost:54324   (sign-in codes arrive here)"
if [ -n "$LAN_IP" ]; then
  echo "  LAN      http://$LAN_IP:54321   (for a physical device)"
fi
